/*
*  This file is part of S:SIMS.
*
*  S:SIMS is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  S:SIMS is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with S:SIMS.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CalcInputWindow.java
 *
 * Created on Sep 7, 2010, 8:54:34 PM
 */

package data_summary;

import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;

/**
 * An spreadsheet window for users to enter values.
 * @author 20378332
 */
public class CalcInputWindow extends javax.swing.JFrame {

    /** Creates new form CalcInputWindow */
    public CalcInputWindow() {
        initComponents();
        this.setTitle("Input Values");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTable = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        inputTable.setModel(DSFrontEnd.inputModel);
        inputTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        inputTable.setName("inputTable"); // NOI18N
        jScrollPane1.setViewportView(inputTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Resets the width of each column to a certain size.
     */
    protected void resetColWidth()    {
        setDefaultTableColumnSize();
        setR0ColumnSize();
    }

    private void setDefaultTableColumnSize() {
        TableColumn column = null;
        for (int i = 0; i < 1; i++) {
            column = inputTable.getColumnModel().getColumn(i);
            column.setPreferredWidth(defaultNameSize);
        }
    }

    private void setR0ColumnSize()  {
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        TableColumn column = null;
        dtcr.setHorizontalAlignment(JLabel.RIGHT);
        int size = inputTable.getColumnCount();

        for (int i = 1; i < size; i++) {
            column = inputTable.getColumnModel().getColumn(i);
            column.setPreferredWidth(r0Size);
            inputTable.setDefaultRenderer(inputTable.getColumnClass(i), dtcr);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inputTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static final int defaultNameSize = 150;
    private final int r0Size = 125;
}
