/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataSummary.java
 *
 * Created on Aug 24, 2010, 3:04:49 PM
 */

package data_summary;
import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;

/**
 * GUI component for data summary subsystem. This handles
 * all gui components and event listeners.
 * @author 20378332
 */
public class DataSummaryWindow extends javax.swing.JFrame {

    /** Creates new form DataSummary */
    public DataSummaryWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exportMenu = new javax.swing.JMenuItem();

        setName(""); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        summaryTable.setModel(DataSummaryFrontEnd.tableModel);
        summaryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        summaryTable.setName("summaryTable"); // NOI18N
        jScrollPane1.setViewportView(summaryTable);

        jMenuBar1.setBorder(null);
        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setName("jMenu1"); // NOI18N

        exportMenu.setName("exportMenu"); // NOI18N
        jMenu1.add(exportMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Resets the width of each column to default values.
     */
    protected void resetColWidth()    {
        setDefaultTableColumnSize();
        setR0ColumnSize();
    }

    private void setDefaultTableColumnSize() {
        TableColumn column = null;
        for (int i = 0; i < 7; i++) {
            column = summaryTable.getColumnModel().getColumn(i);
            column.setPreferredWidth(defaultColWidth[i]);
        }
    }

    private void setR0ColumnSize()  {
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        TableColumn column = null;
        dtcr.setHorizontalAlignment(JLabel.RIGHT);
        int size = summaryTable.getColumnCount();

        for (int i = 7; i < size; i++) {
            column = summaryTable.getColumnModel().getColumn(i);
            column.setPreferredWidth(r0Size);
            summaryTable.setDefaultRenderer(summaryTable.getColumnClass(i), dtcr);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exportMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable summaryTable;
    // End of variables declaration//GEN-END:variables

    private int[] defaultColWidth = {40,30,30,100,100,120,120};
    private final int r0Size = 120;
}
