/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DSGraphWindow.java
 *
 * Created on Sep 2, 2010, 4:44:14 AM
 */

package graph;

import java.awt.image.*;
import java.awt.Graphics;
import org.jCharts.axisChart.*;
import org.jCharts.properties.*;

/**
 *
 * @author 20378332
 */
public class GraphWindow extends javax.swing.JFrame {

    private BufferedImage image;
    private AxisChart ac;
    private double min;
    private double max;
    private double scale = 1.0;
    private int totalRot = 0;
    private double offset = 0;
    private int previousY = -1;

    /** Creates new form DSGraphWindow */
    public GraphWindow(AxisChart ac) {
        this.ac = ac;
        min = ((DataAxisProperties) ac.getAxisProperties().getYAxisProperties()).getUserDefinedMinimumValue();
        max = min + ((DataAxisProperties) ac.getAxisProperties().getYAxisProperties()).getUserDefinedIncrement() * 12;
        GraphFunctions.reScale(ac, min, max, scale, offset);
        image = GraphFunctions.getImage(ac);
        initComponents();

        image = GraphFunctions.setSize(image, this.getWidth() - 20, this.getHeight() - 40);
        paint(this.getGraphics());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Graph");
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        image = GraphFunctions.getImage(ac);
        image = GraphFunctions.setSize(image, this.getWidth() - 20, this.getHeight() - 40);
    }//GEN-LAST:event_formComponentResized

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        paint(this.getGraphics());
    }//GEN-LAST:event_formComponentShown

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        int numOfRotation = evt.getWheelRotation();
        totalRot += numOfRotation;
        scale = Math.exp(totalRot);
        GraphFunctions.reScale(ac, min, max, scale, offset);
        image = GraphFunctions.getImage(ac);
        image = GraphFunctions.setSize(image, this.getWidth() - 20, this.getHeight() - 40);
        paint(this.getGraphics());
    }//GEN-LAST:event_formMouseWheelMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (previousY == -1)
            previousY = evt.getY();
        else {
            int newY = evt.getY();
            double scaleIncrease = (double)Math.abs(previousY - newY) / (double)this.getHeight();
            scaleIncrease *= 13;

            if (newY > previousY)   {
                offset -= scaleIncrease;
            } else if (newY < previousY) {
                offset += scaleIncrease;
            }

            if (newY != previousY)  {
                GraphFunctions.reScale(ac, min, max, scale, offset);
                image = GraphFunctions.getImage(ac);
                image = GraphFunctions.setSize(image, this.getWidth() - 20, this.getHeight() - 40);
                paint(this.getGraphics());
            }

            previousY = newY;
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        previousY = -1;
    }//GEN-LAST:event_formMouseReleased

    public void paint(Graphics g)   {
        //System.err.println("painting");
        super.paint(g);
        // Draw image centered.
        int x = (getWidth() - image.getWidth())/2;
        int y = (getHeight() - image.getHeight())/2;
        g.drawImage(image, x, y + 10, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
