/*
*  This file is part of S:SIMS.
*
*  S:SIMS is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  S:SIMS is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with S:SIMS.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutWindow.java
 * 
 * Created on Sep 24, 2010, 5:44:11 PM
 */

package about;

/**
 * An about window providing a brief description of the project and
 * the external libraries that it uses.
 * @author 20378332
 */
public class AboutWindow extends javax.swing.JFrame {

    private static final String versionId = "2.0.3";

    /** Creates new form AboutWindow */
    public AboutWindow() {
        initComponents();
        insertContent();
        contentField.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        blah = new javax.swing.JScrollPane();
        contentField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About S:SIMS");

        jLabel1.setText("S:SIMS");
        jLabel1.setName("jLabel1"); // NOI18N

        versionLabel.setText("Version");
        versionLabel.setName("versionLabel"); // NOI18N

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        blah.setName("blah"); // NOI18N

        contentField.setColumns(20);
        contentField.setRows(5);
        contentField.setName("contentField"); // NOI18N
        blah.setViewportView(contentField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blah, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(versionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blah, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertContent()    {
        StringBuffer sb = new StringBuffer();

        sb.append("Copyright © 2010 Group J\n\n");
        sb.append("Project Manager : Ragil Prasetya\n");
        sb.append("Developer : Ragil Prasetya\n");
        sb.append("System Testing : Nelson, Joel, James\n");
        sb.append("Members: Bryan, Arjun\n\n");
        sb.append("Credit to :\n");
        sb.append("-- JCharts <http://jcharts.sourceforge.net/>\n");
        sb.append("-- JFreeCharts <http://www.jfree.org/jfreechart/>\n");
        sb.append("-- NSIS <http://nsis.sourceforge.net/>\n\n");
        sb.append("For enquiries contact Ragil at prof_comp_group_j@googlegroups.com");

        contentField.setText(sb.toString());
        versionLabel.setText("Version : " + versionId);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane blah;
    private javax.swing.JTextArea contentField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables

}
