/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileList.java
 *
 * Created on Aug 24, 2010, 3:21:26 PM
 */

package file_list;

import DataStructure.DataHouse;
import javax.swing.DefaultListModel;
import java.util.*;

/**
 * GUI component of file list subsystem. This is the main window
 * that users will interact with. This handles all GUI components
 * and event listeners.
 * @author 20378332
 */
public class FileListWindow extends javax.swing.JFrame {

    /** Creates new form FileList */
    public FileListWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadInputFileMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        showOutputMenuItem = new javax.swing.JMenuItem();
        showSpreadsheetMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMS-2");

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        fileList.setModel(new DefaultListModel());
        fileList.setName("fileList"); // NOI18N
        fileList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fileList);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        fileMenu.setText("File");
        fileMenu.setName("fileMenu"); // NOI18N

        loadInputFileMenu.setText("Load Input File");
        loadInputFileMenu.setName("loadInputFileMenu"); // NOI18N
        loadInputFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInputFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(loadInputFileMenu);

        jMenuItem1.setText("ResetTable");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        exitItem.setText("Exit");
        exitItem.setName("exitItem"); // NOI18N
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);

        windowMenu.setText("Windows");
        windowMenu.setName("windowMenu"); // NOI18N

        showOutputMenuItem.setText("Show Output Window");
        showOutputMenuItem.setName("showOutputMenuItem"); // NOI18N
        showOutputMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOutputMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showOutputMenuItem);

        showSpreadsheetMenuItem.setText("Show Spreadsheet Window");
        showSpreadsheetMenuItem.setName("showSpreadsheetMenuItem"); // NOI18N
        showSpreadsheetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSpreadsheetMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(showSpreadsheetMenuItem);

        jMenuBar1.add(windowMenu);

        helpMenu.setText("Help");
        helpMenu.setName("helpMenu"); // NOI18N
        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadInputFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInputFileMenuActionPerformed
        DataHouse[] dh = FileListFunctions.loadInput();
        if (dh == null)
            return;

        boolean firstDisplayed = false;

        DefaultListModel dlm = (DefaultListModel) fileList.getModel();
        
        for (int i = 0; i < dh.length; i++) {

            if (dh[i] == null)
                continue;

            if (!firstDisplayed)    {
                FileListFunctions.displayData(dh[i]);
                firstDisplayed = true;
            }
            
            dlm.addElement(FileListFunctions.getFileName(dh[i]));
            files.add(dh[i]);
            FileListFunctions.addToSummary(dh[i]);
        }

        FileListFunctions.updateTable();
        FileListFunctions.showOutputWindow();
        FileListFunctions.showSummaryWindow();
    }//GEN-LAST:event_loadInputFileMenuActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    private void showOutputMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOutputMenuItemActionPerformed
        FileListFunctions.showOutputWindow();
    }//GEN-LAST:event_showOutputMenuItemActionPerformed

    private void showSpreadsheetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSpreadsheetMenuItemActionPerformed
        FileListFunctions.showSummaryWindow();
    }//GEN-LAST:event_showSpreadsheetMenuItemActionPerformed

    private void fileListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileListMouseClicked
        int index = fileList.getSelectedIndex();

        if (index != lastIndex) {
            FileListFunctions.displayData(files.get(index));
            lastIndex = index;
        }
    }//GEN-LAST:event_fileListMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FileListFunctions.resetTable();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JList fileList;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem loadInputFileMenu;
    private javax.swing.JMenuItem showOutputMenuItem;
    private javax.swing.JMenuItem showSpreadsheetMenuItem;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables

    private ArrayList<DataHouse> files = new ArrayList<DataHouse> ();
    private int lastIndex = -1;
}
